#!/bin/sh
WINE_USER_ROOT="$1"

Wine_Download_Resource ()
{
	# Download a file and place it in the resource directory (if it does not exist)
	# Usage: POL_Download_Resource [URL] [MD5] (Folder)

	local URL="$1"
	local SERVER_MD5="$2"
	local SUBFOLDER="$3"
	local ATTEMPT
	[ "$4" ] && ATTEMPT="$4" || ATTEMPT=1
	local FILE="${URL##*/}"
	mkdir -p "$WINE_USER_ROOT/ressources/$SUBFOLDER"
	cd "$WINE_USER_ROOT/ressources/$SUBFOLDER" 
	if [ -e "$FILE" ] && [ "$(POL_MD5_file "$FILE")" = "$SERVER_MD5" ]
	then

	else
		local WTCACHE=""
		[ -d "$HOME/.cache/winetricks" ] && WTCACHE="$(find $HOME/.cache/winetricks -type f -a -iname "$FILE" | tail -n 1)"
		if [ -n "$WTCACHE" ] && [ "$(POL_MD5_file "$WTCACHE")" = "$SERVER_MD5" ]
		then
			ln "$WTCACHE" "$FILE" || cp "$WTCACHE" "$FILE"
		#	POL_Debug_Message "Resource found in winetricks cache"
		elif [ "$URL" = "" ]
		then 

		else
			[ -e "$FILE" ] && rm "$FILE"
			wget "$FILE" "$URL"

		fi
	fi
}

Wine_OverrideDLL() {
	# Override DLLs
	MODE=$1
	[ "$MODE" = "disabled" ] && unset MODE
	shift

	(cat << 'EOF'
REGEDIT4
[HKEY_CURRENT_USER\Software\Wine\DllOverrides]
EOF

	for DLL in "$@"
	do
		echo "\"*$DLL\"=\"$MODE\""
	done) > "$WINE_USER_ROOT/tmp/override-dll.reg"

	wine regedit "$WINE_USER_ROOT/tmp/override-dll.reg"
	rm "$WINE_USER_ROOT/tmp/override-dll.reg"
}


# Setting OS check Fix
Set_OS "winxp" "sp3"
cat << EOF > "dotnet40_fix.reg"
[HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows NT\\CurrentVersion]
"ProductName"="Microsoft Windows XP"
"CSDVersion"="Service Pack 3"
"CurrentVersion"="5.3"
"CurrentBuildNumber"="2600"
[HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Windows]
"CSDVersion"=dword:00000300
EOF
wine regedit "dotnet40_fix.reg"
 
mkdir -p "$WINE_USER_ROOT/ressources/dotnet40"
cd "$WINE_USER_ROOT/ressources/dotnet40"
# Downloading dotnet40
Wine_Download_Resource "http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe" "251743dfd3fda414570524bac9e55381" "dotnet40"
 
# Setting Fix 1
wine --ignore-errors reg delete "HKLM\Software\Microsoft\NET Framework Setup\NDP\v4" /f
rm "$WINEPREFIX"/drive_c/windows/system32/mscoree.dll
WINEDLLOVERRIDES="fusion=b"
export WINEDLLOVERRIDES
wineserver -k
 
# Installing dotnet40 - it will hang with exit code 67, don't worry
wine --ignore-errors dotNetFx40_Full_x86_x64.exe /q /c:"install.exe /q"
 
# Overriding dll
Wine_OverrideDLL "native" "mscoree"
 
# Setting Fix 2
wine --ignore-errors reg add "HKLM\\Software\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full" /v Install /t REG_DWORD /d 0001 /f
wine --ignore-errors reg add "HKLM\\Software\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full" /v Version /t REG_SZ /d "4.0.30319" /f
 
unset WINEDLLOVERRIDES
wineserver -k
