name: ags-editor
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: ags-editor is the IDE for creating and running videogames of adventure (aka "quest") genre.
description: |
 Adventure Game Studio (AGS) - is the IDE and the engine meant for creating and running videogames of adventure (aka "quest") genre. 
 It has potential, although limited, support for other genres as well. 
 Originally created by Chris Jones back in 1999, AGS was opensourced in 2011 and since continued to be developed by contributors.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
    run-on: [amd64, i386]

apps:
  ags-editor:
    command: ags-editor
    desktop: usr/share/applications/ags-editor.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, hardware-observe, process-control, cups-control, removable-media ]

parts:
  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      dpkg --add-architecture i386
      apt update

  wine-3p1:
    after: [enable-i386]
    plugin: dump
    source: https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-stable-i386_3.0.0~xenial_i386.deb
    source-type: deb
    override-build: |
      snapcraftctl build
      spi=$SNAPCRAFT_PART_INSTALL
      lins=$spi/usr/share/lintian
      docs=$spi/usr/share/doc
      mans=$spi/usr/share/man
      ws=opt/wine-stable
      cp -r $ws/* $spi/ && cp -r $spi/share $spi/usr/ && rm -r $spi/opt $spi/share $mans $lins $docs
    stage-packages:
      - libfreetype6:i386
      - libpng12-0:i386
      - libncurses5:i386
      - libgnutls30:i386
      - libxext6:i386
      - libudev1:i386
      - libc6:i386
      - libxrender1:i386
      - zlib1g:i386

  wine-3p2:
    plugin: dump
    source: https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-stable_3.0.0~xenial_i386.deb
    source-type: deb
    override-build: |
      snapcraftctl build
      spi=$SNAPCRAFT_PART_INSTALL
      docs=$spi/usr/share/doc
      mans=$spi/share/man
      ws="opt/wine-stable"
      cp -r $ws/* $spi/ && rm -r $spi/opt $docs $mans $spi/share/wine/fonts

  ags-editor:
    plugin: nil
    source: ./scripts
    override-build: |
      snapcraftctl build
      set -ex
      echo 3.4.1 > $SNAPCRAFT_STAGE/version
      ./dl_npp
    stage:
      - bin
      - usr
      - share
    build-packages: [wget, icoutils, unzip]
